---
openapi: 3.0.0
info:
  description: Открытое API для работы с сервисом прогнозирования спроса
  version: 1.0.0
  title: Demand Analysis
servers:
- url: 'http://0.0.0.0:5000/api/v1'
tags:
- name: salesData
  description: Информация о продажах за определенный период
paths:
  /hold_winter/prediction:
    post:
      tags:
      - salesData
      summary: Построение модели Холтера Винта для анализа и предсказания спроса.
      description: Модель Холтера Винта для анализа и предсказания спроса.
      operationId: api.hold_winter.prediction
      parameters:
      - name: freq
        in: query
        description: Частота прогнозирования (дни, недели, месяцы)
        required: false
        schema:
          type: string
      - name: column
        in: query
        description: Столбец в файле для анализа
        required: false
        schema:
          type: string
      - name: delimiter
        in: query
        description: Разделитель столбцов
        required: false
        schema:
          type: string
      - name: period
        in: query
        description: Период прогнозирования
        required: false
        schema:
          type: number
          format: int32
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/file'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forecast'
        '400':
          description: unsuccessful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_400'
  /arima/prediction:
    post:
      tags:
        - salesData
      summary: Построение модели ARIMA для анализа и предсказания спроса.
      description: Модель ARIMA для анализа и предсказания спроса.
      operationId: api.arima.prediction
      parameters:
        - name: freq
          in: query
          description: Частота прогнозирования (дни, недели, месяцы)
          required: false
          schema:
            type: string
        - name: column
          in: query
          description: Столбец в файле для анализа
          required: false
          schema:
            type: string
        - name: delimiter
          in: query
          description: Разделитель столбцов
          required: false
          schema:
            type: string
        - name: seasonal
          in: query
          description: Периодичность данных (4 - квартальные периоды, 12 - годовые периоды)
          schema:
            type: number
            format: int32
        - name: period
          in: query
          description: Период прогнозирования
          required: false
          schema:
            type: number
            format: int32
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/file'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forecast'
        '400':
          description: unsuccessful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_400'
components:
  schemas:
    file:
      required:
      - file
      type: object
      properties:
        file:
          type: string
          description: Файл с информацией о продажах
          format: binary
    forecast:
      type: object
      properties:
        accuracy:
          type: number
          format: float
          description: Среднеквадратичная ошибка rmse
          example: 127.6
        percentage_accuracy:
          type: number
          format: float
          description: Точность прогноза в процентах
          example: 0.6
        start_period_analysis:
          type: string
          description: Дата начала анализа
          example: 2020-10-03
        end_period_analysis:
          type: string
          description: Дата окончания анализа
          example: 2020-11-03
        start_period_forecast:
          type: string
          description: Дата начала прогнозирования
          example: 2020-11-04
        end_period_forecast:
          type: string
          description: Дата окончания прогнозирования
          example: 2020-12-04
        prediction:
          type: object
          description: Прогнозируемая величина
        origin_data:
          type: object
          description: Исходные данные для анализа
    inline_response_400:
      properties:
        code:
          type: number
          format: int32
          example: 400
          description: Код ошибки
        message:
          type: string
          description: Сообщение ошибки

